### ISSUE TITLE
服务端开服30分钟开始tps骤降，1分钟内服务端崩溃

### ISSUE THREAD

**Issue by Suika99** [GTriXy/GregTech-Leisure-Server#1]
在开服后25-30分钟后基本100%复现
附件为server端日志
[crashes.zip](https://github.com/user-attachments/files/16637144/crashes.zip)

**Comment by GTriXy** [comment]
max-tick-time拉大一点 或者等下版本修复爆栈问题 也可以尝试删除ftb备份转而使用手动备份
