### ISSUE TITLE
服务器玩家一传送到机器旁边就崩溃

### ISSUE THREAD

**Issue by xiaowuliao** [GTriXy/GregTech-Leisure-Server#2]
看报告显示这个报错：
    GregTech (gtceu), Version: 1.3.1
        at TRANSFORMER/gtceu@1.3.1/com.gregtechceu.gtceu.api.recipe.RecipeRunner.fillContent(RecipeRunner.java:86)
推测可能是这个机器的问题（不确定）：gtceu:hv_fluid_drilling_rig
崩溃报告：
[crash-2024-08-18_12.01.22-server.zip](https://github.com/user-attachments/files/16647150/crash-2024-08-18_12.01.22-server.zip)

**Comment by GTriXy** [comment]
你是升级版本导致的吗？ 版本更新后配方改变会导致空指针异常 一般情况多崩溃几次就好了
