### ISSUE TITLE
服务端，使用ftb备份的存档会崩溃，看崩溃日志疑似递归

### ISSUE THREAD

**Issue by kkxej** [GTriXy/GregTech-Leisure-Server#3]
附件为服务端崩溃日志
[crash-2024-08-19_00.16.51-server.txt](https://github.com/user-attachments/files/16653949/crash-2024-08-19_00.16.51-server.txt)

**Comment by GTriXy** [comment]
这是个已知的bug，已经修复，.14.2版本会更新模组https://github.com/GregTechCEu/GregTech-Modern/pull/1741
